### ISSUE TITLE
Adding an Unbind

### ISSUE THREAD

**Issue by ghost** [rawphp/Bootstrap-Confirm-Delete#1]
sorry for my english.

I was using your plugin into my dashboard's crud... so I added it to a multiple rows in a table. but because it has an ajax callback.. it fired multiple times if you used more than 1 time. To avoid I suggest to off() it first before binding click event.

example:
deleteBtn.off().on( 'click', { originalObject: $( this ) }, plugin.settings.callback );

**Comment by rawphp** [comment]
Updated in 2.0.1.
