### ISSUE TITLE
Cancel callback issue

### ISSUE THREAD

**Issue by iwansusanto** [rawphp/Bootstrap-Confirm-Delete#5]
I'am using cancel callback

``cancel_callback:    function() { console.log( 'cancel button clicked' ); }``

but console still empty

**Comment by iwansusanto** [comment]
Replace line 49 on bootstrap-confirm-delete.js with 

`$( 'body' ).append( '<div id="bootstrap-confirm-delete-container"><div id="bootstrap-confirm-dialog" class="modal fade"><div class="modal-dialog modal-sm"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><h4 id="bootstrap-confirm-dialog-heading"></h4></div><div class="modal-body"><p id="bootstrap-confirm-dialog-text"></p></div><div class="modal-footer"><a id="bootstrap-confirm-dialog-cancel-delete-btn" type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</a><a id="bootstrap-confirm-dialog-delete-btn" href="#" class="btn btn-danger pull-right">Delete</a></div></div></div></div></div>' `);``

Now, cancel_callback can be used normaly

**Comment by rawphp** [comment]
Fixed in https://github.com/rawphp/Bootstrap-Confirm-Delete/tree/2.1.3
